# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-08 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtendDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=40, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bitcoin_private_key', models.CharField(blank=True, max_length=100, null=True)),
                ('bitcoin_public_key', models.CharField(blank=True, max_length=100, null=True)),
                ('neo_public_key', models.CharField(blank=True, max_length=100, null=True)),
                ('neo_private_key', models.CharField(blank=True, max_length=100, null=True)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
