# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erc20tokens',
            name='decimals',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
