# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-20 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoBasketUserMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service1.CryptoBasket')),
            ],
        ),
    ]
