# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0002_erc20tokens_decimals'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefinedBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_id', models.CharField(max_length=100)),
                ('basket_name', models.CharField(max_length=100)),
                ('coin_id', models.CharField(max_length=10)),
            ],
        ),
    ]
