# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-20 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0003_cryptobasketusermapping_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptobasketusermapping',
            name='crypto_basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service1.CryptoBasket', unique=True),
        ),
    ]
