# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0003_userdefinedbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocoins',
            name='allocation_percent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='erc20tokens',
            name='allocation_percent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
