# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-21 22:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0004_auto_20171020_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCoinsNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=10, unique=True)),
                ('coin_name', models.CharField(blank=True, max_length=50, null=True)),
                ('coin_ticker', models.CharField(blank=True, max_length=20, null=True)),
                ('coin_current_value_btc', models.CharField(blank=True, max_length=50, null=True)),
                ('json_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewCryptoBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_id', models.CharField(max_length=20, unique=True)),
                ('basket_name', models.CharField(max_length=100)),
                ('basket_info', models.TextField(blank=True, null=True)),
                ('json_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
