# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service1', '0004_auto_20171015_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_id', models.CharField(max_length=100)),
                ('coin_id', models.CharField(max_length=100)),
                ('allocation_percent', models.CharField(blank=True, max_length=10, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cryptocoins',
            name='allocation_percent',
        ),
        migrations.RemoveField(
            model_name='erc20tokens',
            name='allocation_percent',
        ),
    ]
