# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-21 23:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service1', '0005_cryptocoinsnew_newcryptobasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcryptobasket',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
