# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0005_auto_20171015_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocoins',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='erc20tokens',
            name='belongs_to',
        ),
    ]
