# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0006_auto_20171015_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocoins',
            name='ticker_api',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erc20tokens',
            name='ticker_api',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
