# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0007_newcryptobasket_amount_allocated'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBasketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('close', models.CharField(blank=True, max_length=20, null=True)),
                ('coin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service1.CryptoCoinsNew')),
            ],
        ),
    ]
