# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0008_historicalbasketdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocoinsnew',
            name='current_price_dollar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
