# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0009_cryptocoinsnew_current_price_dollar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcryptobasket',
            name='amount_allocated',
        ),
        migrations.AddField(
            model_name='newcryptobasket',
            name='amount_on_basket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newcryptobasket',
            name='buy_or_sell',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
