# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0010_auto_20171102_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcryptobasket',
            name='amount_on_basket',
        ),
        migrations.AddField(
            model_name='newcryptobasket',
            name='price_on_creation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
