# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0011_auto_20171102_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptobasketusermapping',
            name='crypto_basket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service1.CryptoBasket'),
        ),
    ]
