# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0012_auto_20171102_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyBasketExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.CharField(blank=True, max_length=20, null=True)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('expiration_date', models.CharField(blank=True, max_length=10, null=True)),
                ('basket_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service1.NewCryptoBasket')),
            ],
        ),
    ]
