# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 12:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0014_buybasketextension_negotiable_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellBasketExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.CharField(blank=True, max_length=20, null=True)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('negotiable_price', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newcryptobasket',
            name='buy_or_sell',
        ),
        migrations.AddField(
            model_name='sellbasketextension',
            name='basket_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service1.NewCryptoBasket'),
        ),
    ]
