# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 14:03
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front_end', '0002_erc20address_network_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenBasketOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_id', models.CharField(max_length=10)),
                ('order_id', models.CharField(max_length=40)),
                ('seller_token_address_qty', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ether_asked', models.CharField(max_length=20)),
                ('is_pulled', models.BooleanField()),
                ('transaction_id', models.TextField(default=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
