# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0004_tradablesets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradablesets',
            name='network_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
