# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0005_tradablesets_network_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradablesets',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
